### ISSUE TITLE
How to create data?

### ISSUE THREAD

**Issue by Adolfhill** [mingcv/Bread#1]
I have download datasets, but I have no idea about how to creat data. 
I read the code and found that I need eval/images eval/targets train/images_aug train/targets to train. Could you please tell me how to perpare these for folder? thanks so much!

**Comment by mingcv** [comment]
Please check out the "exposure_augment.py" or I will mail you all the data in our paper if you provide your e-mail address.

**Comment by Adolfhill** [comment]
Good evening
&nbsp; &nbsp; i apologize for not reply you in time. I was infected with covid-19 so i had no energy to do that.
&nbsp; &nbsp; if you could email all the data in your paper to this mail, i would be very appreciate it.




画图影响幸福人生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mingcv/Bread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mingcv/Bread] How to create data? (Issue #1)





 
Please check out the "exposure_augment.py" or I will mail you all the data in our paper if you provide your e-mail address.

**Comment by mingcv** [comment]
> Good evening &nbsp; &nbsp; i apologize for not reply you in time. I was infected with covid-19 so i had no energy to do that. &nbsp; &nbsp; if you could email all the data in your paper to this mail, i would be very appreciate it. 画图影响幸福人生 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mingcv/Bread" ***@***.***&gt;; 发送时间:&nbsp;2022年11月29日(星期二) 晚上6:51 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mingcv/Bread] How to create data? (Issue #1) Please check out the "exposure_augment.py" or I will mail you all the data in our paper if you provide your e-mail address. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Sorry, but it seems your email address is anonymous.

**Comment by Adolfhill** [comment]
oh i am sorry about that. this is my first time replying email this way. my email address is ***@***.***
thanks so much


画图影响幸福人生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mingcv/Bread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月17日(星期六) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mingcv/Bread] How to create data? (Issue #1)





  
Good evening &nbsp; &nbsp; i apologize for not reply you in time. I was infected with covid-19 so i had no energy to do that. &nbsp; &nbsp; if you could email all the data in your paper to this mail, i would be very appreciate it. 画图影响幸福人生 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mingcv/Bread" @.&gt;; 发送时间:&nbsp;2022年11月29日(星期二) 晚上6:51 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mingcv/Bread] How to create data? (Issue #1) Please check out the "exposure_augment.py" or I will mail you all the data in our paper if you provide your e-mail address. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Sorry, but it seems your email address is anonymous.

**Comment by mingcv** [comment]
Sorry for let you wait so long for the e-mail issues, and just want to inform you that we have released the training data that you may want.

> oh i am sorry about that. this is my first time replying email this way. my email address is ***@***.*** thanks so much 画图影响幸福人生 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mingcv/Bread" ***@***.***&gt;; 发送时间:&nbsp;2022年12月17日(星期六) 中午11:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mingcv/Bread] How to create data? (Issue #1) Good evening &nbsp; &nbsp; i apologize for not reply you in time. I was infected with covid-19 so i had no energy to do that. &nbsp; &nbsp; if you could email all the data in your paper to this mail, i would be very appreciate it. 画图影响幸福人生 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mingcv/Bread" @.&gt;; 发送时间:&nbsp;2022年11月29日(星期二) 晚上6:51 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mingcv/Bread] How to create data? (Issue #1) Please check out the "exposure_augment.py" or I will mail you all the data in our paper if you provide your e-mail address. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; Sorry, but it seems your email address is anonymous. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
