### ISSUE TITLE
Learn about FuseNet

### ISSUE THREAD

**Issue by userjiangxin** [mingcv/Bread#2]
Hello author, I would like to know more about the design of FuseNet in NFM modules and CAN modules, can you tell me where it comes from？

**Comment by mingcv** [comment]
1. It is defined as follows, which is a u-shaped network with attention blocks for fusing features: 
https://github.com/mingcv/Bread/blob/e813c6de477072f1259f6a67dc7a9087c27d18aa/models/networks/networks.py#L43-L60

2. Moreover, you can refer to our IJCV version at [this link](https://link.springer.com/article/10.1007/s11263-022-01667-9) for a clearer explanation, which may be made publicly available after a couple of days.

**Comment by userjiangxin** [comment]
Thank you so much

**Comment by mingcv** [comment]
It seems that there is no further problem.

**Comment by mingcv** [comment]
It seems that there is no further problem.
