### ISSUE TITLE
I try to run train_MECAN.py,but it is always out of memory.my gpu is 3090(24g),batch_size is 1.And can you send the dataset to me,my email is 2956191979@qq.com.Thankyou very much.

### ISSUE THREAD

**Issue by woyuni** [mingcv/Bread#3]
![image](https://user-images.githubusercontent.com/48710812/224888366-d5485449-d0b8-4a51-a9e3-bd7e140ad0f4.png)

**Comment by mingcv** [comment]
1. We rescale the images in SICE dataset to meet the hardware requirements. 
2. Datasets needed by training our models are released in README.md (that is [SICE](https://drive.google.com/file/d/1OTNP-QJ3Nade5my04A2iYVTY77IQBEMf/view?usp=sharing) and [Augmented LOL](https://drive.google.com/file/d/1gyX2kYJWuj3C00eobd49MjRuNbZ29dqN/view?usp=sharing)).

**Comment by woyuni** [comment]
thank you for your answer

**Comment by mingcv** [comment]
You're welcome. For any further issues, don't hesitate to get in touch with us.
> thank you for your answer
