### ISSUE TITLE
Mismatch is size of tensor while using eval_Bread.py 

### ISSUE THREAD

**Issue by himprakashdas** [mingcv/Bread#7]
Error:
RuntimeError: The size of tensor a (1365) must match the size of tensor b (1364) at non-singleton dimension 2. 

Reason:
Basically there is the main input texture size texture_in extracted directly from image then there is the texture illumination, in which dimension reduction is done first and then restored back to normal.

first F.interpolate to calculate texure_in_down with scale factor 0.5 halves 1365 and gives 682 (since it has to be an integer, so 682.5 becomes 682) 

second F.interpolate to calculate texture_illumi restores the dimension by doubling it(previously halved) - 682 * 2  is 1384 which is 1 less than 1385 the actual dimension.

Can you help me fix this?

**Comment by mingcv** [comment]
It is a common problem that UNet-based models can only process the images with scales multiplied by $2^N$, where N represents the number of downsampling layers in the network. So, please round the size of your input image into $1365//(2^N)\times2^N$, e.g., 32 in our case, and thus the new size is $1365//32\times32=1344$.

**Comment by mingcv** [comment]
Since there are no further questions, we'll go ahead and close this issue for now. If you have additional questions in the future, feel free to open a new issue.
