### ISSUE TITLE
Images produced by Replicate and locally using given checkpoints do not match

### ISSUE THREAD

**Issue by himprakashdas** [mingcv/Bread#8]
Images produced using your replicate at: https://replicate.com/mingcv/bread and images produced locally using given checkpoints at: https://github.com/mingcv/Bread/releases/tag/checkpoints donot match. The replicate images are far better than the ones produced locally. Am I missing any updates on the checkpoints or do I need to set any hyperparameters? Please shed some light on this issue.

**Comment by mingcv** [comment]
For images with irregular illuminations, I suggest not using the NFM, which is a trade-off on both the LOL evaluation dataset and the real datasets (like DICM, LIME, MEF, NPE, and VV) performance. When your application only involves samples like the latter, it is better not to use it.

**Comment by mingcv** [comment]
Our models on the replicate do not involve the NFM module.

**Comment by mingcv** [comment]
It seems that there is no further question, we'll go ahead and close this issue for now. If you have additional questions, feel free to open a new issue.
